openapi: 3.0.1

info:
  title: hyp3-api
  version: ""

security:
  - EarthDataLogin: []

paths:

  /jobs:

    post:
      description: Submits a list of jobs for processing.
      operationId: hyp3_api.handlers.post_jobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_jobs_body"
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs_response"

    get:
      description: Get list of previously run jobs.
      operationId: hyp3_api.handlers.get_jobs
      parameters:
        - name: status_code
          in: query
          schema:
            $ref: "#/components/schemas/status_code"
        - name: start
          in: query
          schema:
            $ref: "#/components/schemas/datetime"
        - name: end
          in: query
          schema:
            $ref: "#/components/schemas/datetime"
        - name: name
          in: query
          schema:
            $ref: "#/components/schemas/name"

      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs_response"

  /jobs/{job_id}:
    get:
      description: Get a previously run job.
      operationId: hyp3_api.handlers.get_job_by_id
      parameters:
        - name: job_id
          in: path
          schema:
            $ref: "#/components/schemas/job_id"
          required: true

      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"

  /user:
    get:
      description: Get information about the logged in user.
      operationId: hyp3_api.handlers.get_user
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"

components:
  schemas:

    post_jobs_body:
      description: List for new jobs to submit for processing.
      type: object
      required:
        - jobs
      additionalProperties: false
      properties:
        validate_only:
          $ref: "#/components/schemas/validate_only"
        jobs:
          $ref: "#/components/schemas/list_of_new_jobs"

    jobs_response:
      description: List of submitted jobs.
      type: object
      required:
        - jobs
      additionalProperties: false
      properties:
        validate_only:
          $ref: "#/components/schemas/validate_only"
        jobs:
          $ref: "#/components/schemas/list_of_jobs"

    user:
      description: Information about a user (quota, user id)
      type: object
      required:
        - user_id
        - quota
      additionalProperties: false
      properties:
        user_id:
          $ref: "#/components/schemas/user_id"
        quota:
          $ref: "#/components/schemas/quota"
        job_names:
          $ref: "#components/schemas/job_names_list"

    quota:
      description: Containes the limit of jobs per month and the amount remaining for a user.
      type: object
      required:
        - max_jobs_per_month
        - remaining
      additionalProperties: false
      properties:
        max_jobs_per_month:
          type: integer
          minimum: 0
        remaining:
          type: integer
          minimum: 0

    job_names_list:
      type: array
      items:
        $ref: "#/components/schemas/name"

    list_of_new_jobs:
      description: Contains a list of new job objects.
      type: array
      minItems: 1
      maxItems: 200
      items:
        $ref: "#/components/schemas/new_job"

    new_job:
      description: Contains user provided information on runnning a new job.
      type: object
      required:
        - job_type
        - job_parameters
      additionalProperties: false
      example:
        job_parameters:
          granules:
            - S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8
        job_type: RTC_GAMMA
        name: Job Name

      properties:
        job_type:
          $ref: "#/components/schemas/job_type"
        job_parameters:
          $ref: "./job_parameters.yml#components/schemas/job_parameters"
        name:
          $ref: "#/components/schemas/name"

    list_of_jobs:
      type: array
      items:
        $ref: "#/components/schemas/job"

    job:
      description: Contains information about a submitted job.
      type: object
      required:
        - job_id
        - user_id
        - job_type
        - job_parameters
        - request_time
        - status_code
      additionalProperties: false
      properties:
        job_id:
          $ref: "#/components/schemas/job_id"
        user_id:
          $ref: "#/components/schemas/user_id"
        job_type:
          $ref: "#/components/schemas/job_type"
        job_parameters:
          $ref: "./job_parameters.yml#components/schemas/job_parameters"
        request_time:
          $ref: "#/components/schemas/datetime"
        status_code:
          $ref: "#/components/schemas/status_code"
        name:
          $ref: "#/components/schemas/name"
        files:
          $ref: "#/components/schemas/list_of_files"
        browse_images:
          $ref: "#/components/schemas/list_of_urls"
        thumbnail_images:
          $ref: "#/components/schemas/list_of_urls"
        expiration_time:
          $ref: "#/components/schemas/datetime"

    validate_only:
      type: boolean
      default: false

    job_id:
      description: Unique identifier for a job
      type: string
      format: uuid
      example: 27836b79-e5b2-4d8f-932f-659724ea02c3

    user_id:
      description: Username from Earthdata Login.
      type: string
      example: myUserId

    job_type:
      description: Type of process to run this job.
      type: string
      example: RTC_GAMMA
      enum:
        - RTC_GAMMA
        - INSAR_GAMMA
        - AUTORIFT

    datetime:
      description: Date and time object formatted according to ISO 8601
      type: string
      format: date-time
      example: 2020-06-04T18:00:03+00:00

    status_code:
      description: Status of a submitted job.
      type: string
      enum:
        - PENDING
        - RUNNING
        - SUCCEEDED
        - FAILED
      example: SUCCEEDED

    name:
      description: User provided text to name the job
      type: string
      minLength: 1
      maxLength: 20
      example: Job Name

    list_of_files:
      description: List of downloadable files generated by the job.
      type: array
      items:
        type: object
        required:
          - filename
          - size
          - url
        additionalProperties: False
        properties:
          filename:
            type: string
          size:
            type: integer
            minimum: 0
          url:
            type: string

    list_of_urls:
      type: array
      items:
        type: string

  securitySchemes:
    EarthDataLogin:
      description: |-
        Authentication requires the user to have an account at urs.earthdata.nasa.gov and log in at auth.asf.alaska.edu
      type: apiKey
      in: cookie
      name: asf-urs
      x-apikeyInfoFunc: hyp3_api.auth.decode_token
