name: Deploy custom prod stacks to AWS

on:
  push:
    tags:
      - 'v*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: hyp3-its-live
            domain: hyp3-its-live.asf.alaska.edu
            template_bucket: cf-templates-3o5lnspmwmzg-us-west-2
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/ITS_LIVE_AUTORIFT.yml
              job_spec/ITS_LIVE_CROP.yml
              job_spec/ITS_LIVE_CROP_BULK.yml
              job_spec/ITS_LIVE_META_BULK.yml
            instance_types: r7gd.2xlarge,r7gd.4xlarge,r7gd.8xlarge
            default_max_vcpus: 2000  # Max: 10,406
            expanded_max_vcpus: 2000  # Max: 10,406
            required_surplus: 0
            security_environment: JPL-public
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/arm64/recommended/image_id

          - environment: hyp3-ak-fire-safe
            domain: hyp3-ak-fire-safe.asf.alaska.edu
            template_bucket: cf-templates-kc34l8cyitfn-us-west-2
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/AK_FIRE_SAFE.yml
              job_spec/INSAR_ISCE_BURST.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-pism-cloud
            domain: pism-cloud.asf.alaska.edu
            template_bucket: cf-templates-1qca1gr649g17-us-west-2
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/INSAR_ISCE_BURST.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-volcsarvatory
            domain: hyp3-volcsarvatory.asf.alaska.edu
            template_bucket: cf-templates-1uzy61g1h6omf-us-west-2
            image_tag: latest
            product_lifetime_in_days: 30
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/INSAR_GAMMA.yml
              job_spec/VOLCSARVATORY_MULTI_BURST.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-a19-jpl
            domain: hyp3-a19-jpl.asf.alaska.edu
            template_bucket: cf-templates-v4pvone059de-us-west-2
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/ARIA_AUTORIFT.yml
              job_spec/ARIA_RAIDER.yml
              job_spec/ARIA_S1_COSEIS.yml
              job_spec/INSAR_ISCE.yml
            instance_types: m6id.xlarge,m6id.2xlarge,m6id.4xlarge,m6id.8xlarge,m6idn.xlarge,m6idn.2xlarge,m6idn.4xlarge,m6idn.8xlarge
            default_max_vcpus: 4000  # Max: 13000
            expanded_max_vcpus: 4000  # Max: 13000
            required_surplus: 0
            security_environment: JPL-public
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-tibet-jpl
            domain: hyp3-tibet-jpl.asf.alaska.edu
            template_bucket: cf-templates-1or0efwqffkgd-us-west-2
            image_tag: latest
            product_lifetime_in_days: 30
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/ARIA_AUTORIFT.yml
              job_spec/ARIA_RAIDER.yml
              job_spec/ARIA_S1_COSEIS.yml
              job_spec/INSAR_ISCE.yml
              job_spec/OPERA_DIST_S1.yml
            instance_types: m6id.xlarge,m6id.2xlarge,m6id.4xlarge,m6id.8xlarge,m6idn.xlarge,m6idn.2xlarge,m6idn.4xlarge,m6idn.8xlarge
            default_max_vcpus: 6400  # Max: 10316
            expanded_max_vcpus: 6400  # Max: 10316
            required_surplus: 0
            security_environment: JPL-public
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-nisar-jpl
            domain: hyp3-nisar-jpl.asf.alaska.edu
            template_bucket: cf-templates-gdeyr9hh8rzs-us-west-2
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/ARIA_AUTORIFT.yml
              job_spec/ARIA_RAIDER.yml
              job_spec/ARIA_S1_COSEIS.yml
              job_spec/INSAR_ISCE.yml
              job_spec/OPERA_DIST_S1.yml
            instance_types: m6id.xlarge,m6id.2xlarge,m6id.4xlarge,m6id.8xlarge,m6idn.xlarge,m6idn.2xlarge,m6idn.4xlarge,m6idn.8xlarge
            default_max_vcpus: 1600  # Max: 1652
            expanded_max_vcpus: 1600  # Max: 1652
            required_surplus: 0
            security_environment: JPL-public
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-avo
            domain: hyp3-avo.asf.alaska.edu
            template_bucket: cf-templates-1x4a21iq1cba7-us-west-2
            image_tag: latest
            product_lifetime_in_days: 365000
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/INSAR_GAMMA.yml
              job_spec/INSAR_ISCE_BURST.yml
              job_spec/INSAR_ISCE_MULTI_BURST.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-watermap
            domain: hyp3-watermap.asf.alaska.edu
            template_bucket: cf-templates-1217di08q7vwl-us-west-2
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/RTC_GAMMA.yml
              job_spec/WATER_MAP.yml
              job_spec/WATER_MAP_EQ.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-streamflow
            domain: hyp3-streamflow.asf.alaska.edu
            template_bucket: cf-templates-15gmiot9prm67-us-west-2
            image_tag: latest
            product_lifetime_in_days: 90
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/RTC_GAMMA.yml
              job_spec/WATER_MAP.yml
              job_spec/WATER_MAP_EQ.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 1600
            expanded_max_vcpus: 1600
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: azdwr-hyp3
            domain: azdwr-hyp3.asf.alaska.edu
            template_bucket: cf-templates-xlga17noink6-us-west-2
            image_tag: latest
            product_lifetime_in_days: 30
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/INSAR_GAMMA.yml
              job_spec/INSAR_ISCE_BURST.yml
              job_spec/INSAR_ISCE_MULTI_BURST.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-cargill
            domain: hyp3-cargill.asf.alaska.edu
            template_bucket: cf-templates-j4kd746vpsuv-us-east-1
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files:  >-
              job_spec/AUTORIFT.yml
              job_spec/INSAR_GAMMA.yml
              job_spec/RTC_GAMMA.yml
              job_spec/INSAR_ISCE_BURST.yml
              job_spec/INSAR_ISCE_MULTI_BURST.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 6000  # Max: 6000
            expanded_max_vcpus: 6000  # Max: 6000
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-bgc-engineering
            domain: hyp3-bgc-engineering.asf.alaska.edu
            template_bucket: cf-templates-ez0805f6vy20-us-west-2
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/AUTORIFT.yml
              job_spec/INSAR_GAMMA.yml
              job_spec/RTC_GAMMA.yml
              job_spec/INSAR_ISCE_BURST.yml
              job_spec/INSAR_ISCE_MULTI_BURST.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-carter
            domain: hyp3-carter.asf.alaska.edu
            template_bucket: cf-templates-1qx2mwia5g4kh-us-west-2
            image_tag: latest
            product_lifetime_in_days: 30
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/AUTORIFT.yml
              job_spec/INSAR_GAMMA.yml
              job_spec/RTC_GAMMA.yml
              job_spec/INSAR_ISCE_BURST.yml
              job_spec/INSAR_ISCE_MULTI_BURST.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

          - environment: hyp3-lavas
            domain: hyp3-lavas.asf.alaska.edu
            template_bucket: cf-templates-10a5pjrsv3cgo-us-west-2
            image_tag: latest
            product_lifetime_in_days: 14
            default_credits_per_user: 0
            default_application_status: APPROVED
            cost_profile: DEFAULT
            job_files: >-
              job_spec/INSAR_ISCE_BURST.yml
              job_spec/SRG_GSLC.yml
              job_spec/SRG_TIME_SERIES.yml
            instance_types: r6id.xlarge,r6id.2xlarge,r6id.4xlarge,r6id.8xlarge,r6idn.xlarge,r6idn.2xlarge,r6idn.4xlarge,r6idn.8xlarge
            default_max_vcpus: 640
            expanded_max_vcpus: 640
            required_surplus: 0
            security_environment: ASF
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

    environment:
      name: ${{ matrix.environment }}
      url: https://${{ matrix.domain }}

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.V2_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.V2_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.V2_AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - run: |
          jq -n '{"Parameters": $ARGS.named}' \
            --arg VpcId '${{ secrets.VPC_ID }}' \
            --arg SubnetIds '${{ secrets.SUBNET_IDS }}' \
            --arg SecretArn '${{ secrets.SECRET_ARN }}' \
            --arg ImageTag '${{ matrix.IMAGE_TAG }}' \
            --arg ProductLifetimeInDays '${{ matrix.product_lifetime_in_days }} ' \
            --arg AuthPublicKey '${{ secrets.AUTH_PUBLIC_KEY }}' \
            --arg DefaultCreditsPerUser '${{ matrix.default_credits_per_user }}' \
            --arg DefaultApplicationStatus '${{ matrix.default_application_status }}' \
            --arg AmiId '${{ matrix.ami_id }}' \
            --arg DefaultMaxvCpus '${{ matrix.default_max_vcpus }}' \
            --arg ExpandedMaxvCpus '${{ matrix.expanded_max_vcpus }}' \
            --arg MonthlyBudget '${{ secrets.MONTHLY_BUDGET }}' \
            --arg RequiredSurplus '${{ matrix.required_surplus }}' \
            --arg InstanceTypes '${{ matrix.instance_types }}' \
            --arg DomainName '${{ matrix.domain }}' \
            --arg CertificateArn '${{ secrets.CERTIFICATE_ARN }}' \
            > parameters.json

      - uses: ./.github/actions/deploy-hyp3
        with:
          TEMPLATE_BUCKET:  ${{ matrix.template_bucket }}
          STACK_NAME: ${{ matrix.environment }}
          API_NAME: ${{ matrix.environment }}
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          COST_PROFILE: ${{ matrix.cost_profile }}
          JOB_FILES: ${{ matrix.job_files }}
          SECURITY_ENVIRONMENT: ${{ matrix.security_environment }}
          PARAMETER_FILE: parameters.json
